const data = [
  {
    id: 1486781,
    url: 'https://www.tvmaze.com/episodes/1486781/the-simpsons-30x01-barts-not-dead',
    name: 'Bart\'s Not Dead',
    season: 30,
    number: 1,
    type: 'regular',
    airdate: '2018-09-30',
    airtime: '20:00',
    airstamp: '2018-10-01T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/169/423812.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/169/423812.jpg',
    },
    summary: '<p>Bart takes a dare, and ends up in the hospital. To cover for himself and Homer, he says he went to Heaven and met Jesus. Christian producers offer the Simpsons a movie deal, which Homer takes. But Bart can\'t deal with the guilt and comes clean to Marge after the movie is finished.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1486781',
      },
    },
  },
  {
    id: 1528795,
    url: 'https://www.tvmaze.com/episodes/1528795/the-simpsons-30x02-heartbreak-hotel',
    name: 'Heartbreak Hotel',
    season: 30,
    number: 2,
    type: 'regular',
    airdate: '2018-10-07',
    airtime: '20:00',
    airstamp: '2018-10-08T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/170/426501.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/170/426501.jpg',
    },
    summary: '<p>Marge and Homer\'s marriage is tested when they travel to a tropical island to compete for a million dollars on Marge\'s favorite reality competition show.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1528795',
      },
    },
  },
  {
    id: 1528796,
    url: 'https://www.tvmaze.com/episodes/1528796/the-simpsons-30x03-my-way-or-the-highway-to-heaven',
    name: 'My Way or the Highway to Heaven',
    season: 30,
    number: 3,
    type: 'regular',
    airdate: '2018-10-14',
    airtime: '20:00',
    airstamp: '2018-10-15T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/171/428823.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/171/428823.jpg',
    },
    summary: '<p>God and St. Peter contemplate what merits a soul getting into heaven, while citizens of Springfield remember their divine encounters.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1528796',
      },
    },
  },
  {
    id: 1528797,
    url: 'https://www.tvmaze.com/episodes/1528797/the-simpsons-30x04-treehouse-of-horror-xxix',
    name: 'Treehouse of Horror XXIX',
    season: 30,
    number: 4,
    type: 'regular',
    airdate: '2018-10-21',
    airtime: '20:00',
    airstamp: '2018-10-22T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/172/431071.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/172/431071.jpg',
    },
    summary: '<p>Homer wins an oyster-eating contest against the mythical Cthulhu, Springfield is overrun by plant body-snatchers, Lisa finally snaps and Mr. Burns opens a retirement home with some Jurassic upgrades.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1528797',
      },
    },
  },
  {
    id: 1544184,
    url: 'https://www.tvmaze.com/episodes/1544184/the-simpsons-30x05-baby-you-cant-drive-my-car',
    name: 'Baby You Can\'t Drive My Car',
    season: 30,
    number: 5,
    type: 'regular',
    airdate: '2018-11-04',
    airtime: '20:00',
    airstamp: '2018-11-05T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/173/434644.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/173/434644.jpg',
    },
    summary: '<p>A self-driving car company comes to Springfield, poaching all of the power plant employees with its fun work environment.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1544184',
      },
    },
  },
  {
    id: 1548324,
    url: 'https://www.tvmaze.com/episodes/1548324/the-simpsons-30x06-from-russia-without-love',
    name: 'From Russia Without Love',
    season: 30,
    number: 6,
    type: 'regular',
    airdate: '2018-11-11',
    airtime: '20:00',
    airstamp: '2018-11-12T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/174/436390.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/174/436390.jpg',
    },
    summary: '<p>On a mission to play hardcore pranks, Bart, Nelson and Milhouse get Moe a mail-order bride on the Dark Web.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1548324',
      },
    },
  },
  {
    id: 1552433,
    url: 'https://www.tvmaze.com/episodes/1552433/the-simpsons-30x07-werking-mom',
    name: 'Werking Mom',
    season: 30,
    number: 7,
    type: 'regular',
    airdate: '2018-11-18',
    airtime: '20:00',
    airstamp: '2018-11-19T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/175/437921.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/175/437921.jpg',
    },
    summary: '<p>Marge wants a job, and stumbles into becoming a plastic food storage container-selling drag queen. Meanwhile, Lisa tries to make the world better in the style of "Amelie"</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1552433',
      },
    },
  },
  {
    id: 1553223,
    url: 'https://www.tvmaze.com/episodes/1553223/the-simpsons-30x08-krusty-the-clown',
    name: 'Krusty the Clown',
    season: 30,
    number: 8,
    type: 'regular',
    airdate: '2018-11-25',
    airtime: '20:00',
    airstamp: '2018-11-26T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/175/439311.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/175/439311.jpg',
    },
    summary: '<p>Homer finds his calling as a TV recapper, but his harsh grading causes a brawl with Krusty. After almost killing Homer, Krusty hides out at a real circus, and finds happiness there.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1553223',
      },
    },
  },
  {
    id: 1553224,
    url: 'https://www.tvmaze.com/episodes/1553224/the-simpsons-30x09-daddicus-finch',
    name: 'Daddicus Finch',
    season: 30,
    number: 9,
    type: 'regular',
    airdate: '2018-12-02',
    airtime: '20:00',
    airstamp: '2018-12-03T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/176/441055.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/176/441055.jpg',
    },
    summary: '<p>Lisa and Homer\'s bond gets stronger when they start spending real quality time together, and Bart feels neglected. So Marge tries to help Homer balance his attention between the kids.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1553224',
      },
    },
  },
  {
    id: 1553225,
    url: 'https://www.tvmaze.com/episodes/1553225/the-simpsons-30x10-tis-the-30th-season',
    name: '\'Tis the 30th Season',
    season: 30,
    number: 10,
    type: 'regular',
    airdate: '2018-12-09',
    airtime: '20:00',
    airstamp: '2018-12-10T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/176/442342.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/176/442342.jpg',
    },
    summary: '<p>After a failed Black Friday shopping spree, Marge is determined to fix Christmas. However, Homer and the kids surprise Marge with a vacation to a Florida resort.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1553225',
      },
    },
  },
  {
    id: 1577397,
    url: 'https://www.tvmaze.com/episodes/1577397/the-simpsons-30x11-mad-about-the-toy',
    name: 'Mad About the Toy',
    season: 30,
    number: 11,
    type: 'regular',
    airdate: '2019-01-06',
    airtime: '20:00',
    airstamp: '2019-01-07T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/179/448451.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/179/448451.jpg',
    },
    summary: '<p>When Marge and Homer leave Grampa to babysit the kids, some little green army men trigger a PTSD episode, sending the family on a journey to Grampa\'s past to when he was a post-war toy model.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1577397',
      },
    },
  },
  {
    id: 1577398,
    url: 'https://www.tvmaze.com/episodes/1577398/the-simpsons-30x12-the-girl-on-the-bus',
    name: 'The Girl on the Bus',
    season: 30,
    number: 12,
    type: 'regular',
    airdate: '2019-01-13',
    airtime: '20:00',
    airstamp: '2019-01-14T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/180/450212.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/180/450212.jpg',
    },
    summary: '<p>When Lisa spots a new best friend from the window of the bus, she gets a taste of what life could be like with a different, more cultured family, and proceeds to try and live a double life.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1577398',
      },
    },
  },
  {
    id: 1592852,
    url: 'https://www.tvmaze.com/episodes/1592852/the-simpsons-30x13-im-dancing-as-fat-as-i-can',
    name: 'I\'m Dancing as Fat as I Can',
    season: 30,
    number: 13,
    type: 'regular',
    airdate: '2019-02-10',
    airtime: '20:00',
    airstamp: '2019-02-11T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/183/458693.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/183/458693.jpg',
    },
    summary: '<p>Homer angers Marge by binging their favorite show without her, and has to pick up a new skill in order to make amends. Meanwhile, Bart prepares to compete in "Krusty\'s Holiday Trample".</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1592852',
      },
    },
  },
  {
    id: 1596123,
    url: 'https://www.tvmaze.com/episodes/1596123/the-simpsons-30x14-the-clown-stays-in-the-picture',
    name: 'The Clown Stays in the Picture',
    season: 30,
    number: 14,
    type: 'regular',
    airdate: '2019-02-17',
    airtime: '20:00',
    airstamp: '2019-02-18T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/184/461020.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/184/461020.jpg',
    },
    summary: '<p>Krusty reveals the untold story of his past in his movie "The Sands of Space." While working as personal assistants on the movie, Bart and Lisa learn about the early years of their parents\' relationship.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1596123',
      },
    },
  },
  {
    id: 1610363,
    url: 'https://www.tvmaze.com/episodes/1610363/the-simpsons-30x15-101-mitigations',
    name: '101 Mitigations',
    season: 30,
    number: 15,
    type: 'regular',
    airdate: '2019-03-03',
    airtime: '20:00',
    airstamp: '2019-03-04T01:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/186/466419.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/186/466419.jpg',
    },
    summary: '<p>After Homer steals Comic Book Guy\'s car, he must either prove his innocence in court or reconcile with the jilted nerd.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1610363',
      },
    },
  },
  {
    id: 1610370,
    url: 'https://www.tvmaze.com/episodes/1610370/the-simpsons-30x16-i-want-you-shes-so-heavy',
    name: 'I Want You (She\'s So Heavy)',
    season: 30,
    number: 16,
    type: 'regular',
    airdate: '2019-03-10',
    airtime: '20:00',
    airstamp: '2019-03-11T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/187/468546.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/187/468546.jpg',
    },
    summary: '<p>When a romantic night ends in injury, Marge recovers by taking up kiteboarding while Homer bonds with his hallucinated hernia. Lisa attempts to fix her parents\' strained relationship by seeking advice from an unlikely source.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1610370',
      },
    },
  },
  {
    id: 1613237,
    url: 'https://www.tvmaze.com/episodes/1613237/the-simpsons-30x17-e-my-sports',
    name: 'E My Sports',
    season: 30,
    number: 17,
    type: 'regular',
    airdate: '2019-03-17',
    airtime: '20:00',
    airstamp: '2019-03-18T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/188/471539.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/188/471539.jpg',
    },
    summary: '<p>As Bart begins to excel in video game competitions, Homer discovers a passion for coaching him. Lisa attempts to bring Homer back to reality, but the plan causes chaos.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1613237',
      },
    },
  },
  {
    id: 1616515,
    url: 'https://www.tvmaze.com/episodes/1616515/the-simpsons-30x18-bart-vs-itchy-scratchy',
    name: 'Bart vs. Itchy & Scratchy',
    season: 30,
    number: 18,
    type: 'regular',
    airdate: '2019-03-24',
    airtime: '20:00',
    airstamp: '2019-03-25T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/189/473998.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/189/473998.jpg',
    },
    summary: '<p>Krusty releases an all-female reboot of "Itchy and Scratchy," so Bart and his crew of all-male friends decide to boycott the show. After Bart\'s friends turn on him for laughing at the reboot, Bart joins a woke group of sixth-grade girls who commit crimes against patriarchy.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1616515',
      },
    },
  },
  {
    id: 1619573,
    url: 'https://www.tvmaze.com/episodes/1619573/the-simpsons-30x19-girls-in-the-band',
    name: 'Girl\'s in the Band',
    season: 30,
    number: 19,
    type: 'regular',
    airdate: '2019-03-31',
    airtime: '20:00',
    airstamp: '2019-04-01T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/190/475723.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/190/475723.jpg',
    },
    summary: '<p>Lisa is scouted by the director of the Capitol City Philharmonic, to her band teacher\'s dismay. Homer works extra shifts at the plant so Lisa can play, putting strain on the family.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1619573',
      },
    },
  },
  {
    id: 1628804,
    url: 'https://www.tvmaze.com/episodes/1628804/the-simpsons-30x20-im-just-a-girl-who-cant-say-doh',
    name: 'I\'m Just a Girl Who Can\'t Say D\'oh',
    season: 30,
    number: 20,
    type: 'regular',
    airdate: '2019-04-07',
    airtime: '20:00',
    airstamp: '2019-04-08T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/191/477656.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/191/477656.jpg',
    },
    summary: '<p>Marge becomes Director of Springfield\'s local theater, armed with Lisa\'s script resembling "Hamilton." Meanwhile, Homer joins a baby class with Maggie, where he takes a liking to supervisor Chloe</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1628804',
      },
    },
  },
  {
    id: 1634960,
    url: 'https://www.tvmaze.com/episodes/1634960/the-simpsons-30x21-doh-canada',
    name: 'D\'oh Canada',
    season: 30,
    number: 21,
    type: 'regular',
    airdate: '2019-04-28',
    airtime: '20:00',
    airstamp: '2019-04-29T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/193/484803.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/193/484803.jpg',
    },
    summary: '<p>On a family vacation to Niagara Falls, Lisa is mistakenly granted political asylum in Canada. When Marge goes to rescue Lisa, they are forced to re-evaluate their love for America as they navigate the polite Canadian landscape. Meanwhile, Homer takes Maggie to a "Daddy and Me" class.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1634960',
      },
    },
  },
  {
    id: 1636168,
    url: 'https://www.tvmaze.com/episodes/1636168/the-simpsons-30x22-woo-hoo-dunnit',
    name: 'Woo-Hoo Dunnit',
    season: 30,
    number: 22,
    type: 'regular',
    airdate: '2019-05-05',
    airtime: '20:00',
    airstamp: '2019-05-06T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/195/487863.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/195/487863.jpg',
    },
    summary: '<p>When the secret stack of cash – aka Lisa\'s college fund – Marge keeps under the sink goes missing, the documentary crime series "Deadline Springfield" goes in-depth to solve the case, leaving no stone unturned.</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1636168',
      },
    },
  },
  {
    id: 1636169,
    url: 'https://www.tvmaze.com/episodes/1636169/the-simpsons-30x23-crystal-blue-haired-persuasion',
    name: 'Crystal Blue-Haired Persuasion',
    season: 30,
    number: 23,
    type: 'regular',
    airdate: '2019-05-12',
    airtime: '20:00',
    airstamp: '2019-05-13T00:00:00+00:00',
    runtime: 30,
    image: {
      medium: 'https://static.tvmaze.com/uploads/images/medium_landscape/196/491665.jpg',
      original: 'https://static.tvmaze.com/uploads/images/original_untouched/196/491665.jpg',
    },
    summary: '<p>After Homer\'s work cuts children\'s healthcare benefits, Marge turns to buying healing crystals as a cheaper solution for Bart\'s ADD. Bart begins to succeed in school, prompting Marge to open her very own crystals empire and sell to the naive mothers at school</p>',
    _links: {
      self: {
        href: 'https://api.tvmaze.com/episodes/1636169',
      },
    },
  },
];

export default data;
